#!/bin/bash

## Copyright (C) 2024 - 2024 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -o errexit
set -o nounset
set -o errtrace
set -o pipefail

kernel_cmdline="$(cat /proc/cmdline)"

if [[ "${kernel_cmdline}" =~ 'boot-role=sysmaint' ]]; then
  passwd_exit_code=0
  passwd --unlock sysmaint || passwd_exit_code="$?"

  ## `passwd --unlock` will fail and exit 3 if the account is locked and
  ## passwordless. In this instance, the proper way to unlock the account is
  ## with `passwd -d`.
  if [ "${passwd_exit_code}" = '3' ]; then
    passwd -d sysmaint
  else
    exit "${passwd_exit_code}"
  fi
else
  passwd --lock 'sysmaint'
fi
