#!/bin/bash

## Copyright (C) 2024 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

window_manager_list=(
   '/usr/bin/labwc'
   # Add other window managers here later
)
selected_window_manager=''
for window_manager in "${window_manager_list[@]}"; do
   if [ -e "${window_manager}" ]; then
      selected_window_manager="${window_manager}"
      break
   fi
done

sysmaint_app_list=(
  '/usr/bin/sysmaint-panel'
  '/usr/bin/x-terminal-emulator'
)
selected_sysmaint_app=''
for sysmaint_app in "${sysmaint_app_list[@]}"; do
   if [ -e "${sysmaint_app}" ]; then
      selected_sysmaint_app="${sysmaint_app}"
      break
   fi
done

dbus-update-activation-environment --systemd --all

user_service_list=(
   'polkit-gnome-authentication-agent-1'
   'msgdispatcher'
   'xscreensaver'
   'updatecheck'
)

"${selected_window_manager}" &
# Needed to prevent window ordering problems
sleep 1;
export WAYLAND_DISPLAY=wayland-0
"${selected_sysmaint_app}" &
sysmaint_app_pid="$!"

# Run background processes. These services are usually run as a non-root user
# by way of /etc/xdg/autostart. Running everything in /etc/xdg/autostart would
# be bad here because sysmaint's graphical session is intentionally running as
# few services as possible to keep attack surface low. Instead, just run the
# services we need, if they exist.
for (( i = 0; i < "${#user_service_list[@]}"; i++ )); do
   gio launch "/etc/xdg/autostart/${user_service_list[i]}.desktop" &
done

wait "${sysmaint_app_pid}"
