#!/bin/bash

## Copyright (C) 2024 - 2024 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -o errexit
set -o nounset
set -o errtrace
set -o pipefail

passwd_change_mode="$1";
[ -z "${passwd_change_mode}" ] && exit 1;

if [ "${passwd_change_mode}" = 'lock' ]; then
  passwd --lock 'sysmaint'
elif [ "${passwd_change_mode}" = 'unlock' ]; then
  passwd_exit_code=0
  passwd --unlock sysmaint || passwd_exit_code="$?"

  ## `passwd --unlock` will fail and exit 3 if the account is locked and
  ## passwordless. In this instance, the proper way to unlock the account is
  ## with `passwd -d`.
  if [ "${passwd_exit_code}" = '3' ]; then
    passwd -d sysmaint
  else
    exit "${passwd_exit_code}"
  fi
else
  1>&2 echo 'Unrecognized password change mode provided.';
  exit 1;
fi
