#!/bin/sh

## Copyright (C) 2024 - 2024 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

#set -x

true "user-sysmaint-split $0: START"

set -e
set -o allexport

GRUB_DEVICE="/dev/disk/by-uuid/${GRUB_DEVICE_UUID}"
unset GRUB_DEVICE_UUID
GRUB_DISTRIBUTOR="PERSISTENT mode SYSMAINT (For system maintenance tasks.)"
GRUB_DISABLE_RECOVERY="true"
GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX boot-role=sysmaint systemd.unit=minimal-session.target"
GRUB_DISABLE_LINUX_UUID="true"

if test -x /etc/grub.d/10_linux ; then
	/etc/grub.d/10_linux
fi

true "user-sysmaint-split $0: OK: END"
